---
# main task for role execution
# inventory host and credentials must be created and specified in AWX template
- name: renew the LetsEncrypt cert on a AWS Lightsail Bitnami instance
  hosts: all
  gather_facts: no
  become: true
  
  tasks:
  
  - name: get cert info
    community.crypto.x509_certificate_info:
      path: "{{cert_path}}"
      valid_at:
        point_1: "+1d"
        point_2: "+7d"
    register: cert_info
  
  - name: test cert validity
    assert:
      that:
        - cert_info.valid_at.point_1
        - not cert_info.valid_at.point_2
      quite: yes
      success_msg: cert requires renewal
      fail_msg: cert does not require renewal yet
  
  - debug:
      msg: "end_play"
  #- name: end playbook
  #  meta: end_play

  #- name: renew cert
  #  include_role:
  #    name: renew_cert
