---
# main task for role execution
# inventory host and credentials must be created and specified in AWX template
- name: renew the LetsEncrypt cert on a AWS Lightsail Bitnami instance
  hosts: all
  gather_facts: no
  become: true
  
  vars:
    max_validity: 7 # maximum number of days the certificate can still be valid for it to be renewed
    skip_check: no # validity check can be skipped and the certificate will always be renewed

  tasks:
  
  - name: get current cert info
    community.crypto.x509_certificate_info:
      path: "{{cert_path}}"
      valid_at:
        point_1: "-1m" # true if valid 1 minute ago
        point_2: "+{{ max_validity }}d" # true if valid in number of days specified by max_validity
    register: cert_info

  - name: test cert validity
    assert:
      that:
        - '(not cert_info.valid_at.point_1) or (not cert_info.valid_at.point_2)'
      quiet: true
      success_msg: "cert is expired or is within the {{ max_validity }} days maximum validity period and will be renewed."
      fail_msg: "certificate validity is longer than {{ max_validity }} days and will not be renewed at this time."
    when: not skip_check

  # playbook will fail at this point if the certificate is valid for longer than maximum validity

  - name: renew cert
    include_role:
      name: renew_cert

  - name: get new cert info
    community.crypto.x509_certificate_info:
      path: "{{cert_path}}"
    register: new_cert_info
  
  - name: dump cert info
    debug:
      msg:
        - "CERTIFICATE RENEWAL SUCCESS"
        - "Old cert expiry: {{cert_info.not_after}}"
        - "New cert expiry: {{new_cert_info.not_after}}"
