---
# main task for role execution
# inventory host and credentials must be created and specified in AWX template
- name: renew the LetsEncrypt cert on a AWS Lightsail Bitnami instance
  hosts: all
  gather_facts: no
  become: true
  
  tasks:
  
  - name: get cert info
    community.crypto.x509_certificate_info:
      path: "{{cert_path}}"
    register: cert_info
  
  - name: cert info dump
    debug:
      var: cert_info.not_after
  
  - name: end playbook
    meta: end_play

  - name: renew cert
    include_role:
      name: renew_cert
