---
- name: get current cert info
  community.crypto.x509_certificate_info:
    path: "{{cert_path}}"
    valid_at:
      point_1: "-1m" # true if valid 1 minute ago
      point_2: "+{{ min_validity }}d" # true if valid in number of days specified by min_validity
  register: cert_info

- name: get datetimestamp
  shell: "date +%Y%m%d%H%M%S%z"
  register: tstamp

- name: set datetime vars
  set_fact:
    curr_dt: {{ tstamp.stdout|to_datetime(format="%Y%m%d%H%M%S%z") }}'
    cert_exp_dt: {{ cert_info.not_after|to_datetime(format="%Y%m%d%H%M%S%z") }}'
    days_rem: {{ ((cert_info.not_after|to_datetime(format="%Y%m%d%H%M%S%z")) - (tstamp.stdout|to_datetime(format="%Y%m%d%H%M%S%z"))).days }}'

- name: test cert validity
  assert:
    that:
      - '(not cert_info.valid_at.point_1) or (not cert_info.valid_at.point_2)'
    quiet: true    
    
    success_msg:
      The current certificate expiry was/is {{ cert_exp_dt }}. {{ days_rem }}
      Shorter than the defined minimum validity of {{ min_validity }} days.
      Certificate will be renewed. 
    
    fail_msg:
      The current certificate is valid for {{ days_rem }} days.
      Longer than the defined minimum validity of {{ min_validity }} days.
      Certificate will not be renewed at this time.
  
  when: not skip_check|bool

# playbook will fail at this point if the certificate is valid for longer than maximum validity
