---
- name: get current cert info
  community.crypto.x509_certificate_info:
    path: "{{cert_path}}"
    valid_at:
      point_1: "-1m" # true if valid 1 minute ago
      point_2: "+{{ max_validity }}d" # true if valid in number of days specified by max_validity
  register: cert_info

- name: test cert validity
  assert:
    that:
      - '(not cert_info.valid_at.point_1) or (not cert_info.valid_at.point_2)'
    quiet: true
    
    success_msg: 'The current certificate is expired or is within the {{ max_validity }} days maximum validity period and will be renewed.'
    
    fail_msg: 'The current certificate validity is longer than {{ max_validity }} days and will not be renewed at this time. Certificate will remain valid for another {{cert_info.not_after|to_datetime(format="%Y%m%d%H%M%S%z").days()}} days.'
  when: not skip_check|bool

# playbook will fail at this point if the certificate is valid for longer than maximum validity
